[package]
name = "benchmarks_ltsgraph"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcrl3_lts.workspace = true
mcrl3_ltsgraph-lib = { path = "../library" }

criterion.workspace = true
tiny-skia.workspace = true
rand.workspace = true

[[bench]]
name = "benchmark_ltsgraph"
harness = false