[workspace.package]
authors = ["Maurice Laveaux"]
edition = "2021"
license = "BSL-1.0"
repository = "https://github.com/mlaveaux/mCRL2-rust.git"
rust-version = "1.80.1"
version = "0.1.0"

[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.dependencies]
thiserror = "2.0"
regex = "1.0"
bitstream-io = "2.6"
once_cell = "1.8"
num = "0.4"
hashbrown = "0.15.2"

# Only used for xtask
duct = "0.13"
fs_extra = "1.3"
glob = "0.3"