[workspace.package]
edition = "2024"
homepage = "https://mercorg.github.io/merc-website/"
repository = "https://github.com/MERCorg/merc.git"
license = "BSL-1.0"
rust-version = "1.91.0"
version = "2.0.0"

# Add debug information to the release binaries.
[profile.release]
lto = "thin"
panic = "abort"
debug = "line-tables-only"
split-debuginfo = "packed"

[profile.dev]
split-debuginfo = "packed"

[workspace]
resolver = "3"
members = [
    "crates/aterm",
    "crates/aterm/benchmarks",
    "crates/collections",
    "crates/data",
    "crates/explore",
    "crates/io",
    "crates/ldd",
    "crates/ldd/benchmarks",
    "crates/lts",
    "crates/macros",
    "crates/number",
    "crates/rec-tests",
    "crates/reduction",
    "crates/refinement",
    "crates/sabre_compiling",
    "crates/sabre_compiling/sabre_ffi",
    "crates/sabre",
    "crates/sabre/benchmarks",
    "crates/sharedmutex",
    "crates/sharedmutex/benchmarks",
    "crates/symbolic",
    "crates/syntax",
    "crates/tools",
    "crates/unsafety",
    "crates/unsafety/benchmarks",
    "crates/utilities",
    "crates/utilities/benchmarks",
    "crates/vpg",
    "crates/xtask",
    "tools/lts",
    "tools/rewrite",
    "tools/sym",
    "tools/vpg",
]

[workspace.dependencies]
ahash = "0.8"
bitstream-io = "4.10"
bitvec = "1.1"
boxcar = "0.2"
bumpalo = "3.20"
clap = { version = "4.6", features = ["derive"] }
core_affinity2 = "0.15"
dashmap = { version = "7.0.0-rc2", features = ["inline-more"] }
delegate = "0.13"
env_logger = { version = "0.11", features = ["kv"] }
equivalent = "1.0"
hashbrown = "0.17"
html-escape = "0.2"
itertools = "0.15"
log = { version = "0.4", features = ["kv"] }
num = "0.4"
oxidd = { version = "0.11", features = ["manager-pointer"] }
oxidd-core = "0.11"
oxidd-dump = "0.6"
oxidd-reorder = "0.6"
oxidd-rules-bdd = "0.11"
parking_lot = "0.12"
pest = "2.8"
pest_derive  = "2.8"
rand = "0.10"
rayon = "1.12"
regex = "1.12"
rustc-hash = "2.1"
smallvec = "1.15"
thiserror = "2.0"
toml = "1.1"
winapi = { version = "0.3", features = ["consoleapi", "wincon"] }

# Used for the compiling rewriter
libloading = "0.9"

# Used by the lower level crates
allocator-api2 =  "0.4"
backtrace = "0.3"
crossbeam-deque = "0.8"
crossbeam-utils = "0.8"
loom = { version = "0.7", features = ["checkpoint"] }
mimalloc = "0.1"
streaming-iterator = "0.1"
thread_local = "1.1"
tikv-jemallocator = "0.7"

# Used in macros
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

# Used for xtask
duct = "1.1"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
which = "8.0"

# Used in tests
indoc  = "2.0"
test-case  = "3.3"
test-log = "0.2"
trybuild = "1.0"
tempfile = "3.27"

# Used for benchmarks
criterion = "0.8"

# Used for the cadp FFI
bindgen = "0.72"

# The workspace crates.
merc_aterm = { version = "3.0", path = "crates/aterm" }
merc_collections = { version = "2.0", path = "crates/collections" }
merc_data = { version = "3.0", path = "crates/data" }
merc_explore = { version = "2.0", path = "crates/explore" }
merc_io = { version = "3.0", path = "crates/io" }
merc_ldd = { version = "3.0", path = "crates/ldd" }
merc_lts = { version = "2.0", path = "crates/lts" }
merc_macros = { version = "2.0", path = "crates/macros" }
merc_number = { version = "2.0", path = "crates/number" }
merc_refinement = { version = "2.0", path = "crates/refinement" }
merc_rec-tests = { path = "crates/rec-tests" }
merc_reduction = { version = "3.0", path = "crates/reduction" }
merc_sabre = { version = "2.0", path = "crates/sabre" }
merc_sabre-compiling = { path = "crates/sabre_compiling" }
merc_sabre-ffi = { path = "crates/sabre_compiling/sabre_ffi" }
merc_sharedmutex = { version = "3.0", path = "crates/sharedmutex" }
merc_symbolic = { version = "3.0", path = "crates/symbolic", features = ["clap"] }
merc_syntax = { version = "2.0", path = "crates/syntax" }
merc_tools = { path = "crates/tools" }
merc_unsafety = { version = "3.0", path = "crates/unsafety" }
merc_utilities = { version = "3.0", path = "crates/utilities" }
merc_vpg = { path = "crates/vpg", features = ["clap"] }

# Vendored libraries
merc_pest_consume = { version = "2.0", git = "https://github.com/MERCorg/pest_consume" }
merc_pest_consume_macros = { version = "2.0", git = "https://github.com/MERCorg/pest_consume" }

[workspace.metadata.cargo-semver-checks.lints]
enum_no_repr_variant_discriminant_changed = "allow"
partial_ord_enum_variants_reordered = "allow"