[wokrspace.package]
name = "mCRL3"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.dependencies]
thiserror = "2.0"
regex = "1.0"
bitstream-io = "2.6"
once_cell = "1.8"
num = "0.4"
hashbrown = "0.15.2"