[workspace.package]
authors = ["Maurice Laveaux"]
edition = "2021"
license = "BSL-1.0"
repository = "https://github.com/mlaveaux/mCRL2-rust.git"
rust-version = "1.80.1"
version = "0.1.0"

[workspace]
resolver = "2"
members = [
    "crates/*",
    "tools/release/*",
]

[workspace.dependencies]
bf-shared-mutex = { git = "https://github.com/mlaveaux/bf-shared-mutex" }

thiserror = "2.0"
regex = "1.0"
bitstream-io = "2.6"
once_cell = "1.8"
num = "0.4"
hashbrown = "0.15.2"
pest = "2.7"
pest_derive  = "2.7"
pest_consume  = "1.1"
log = "0.4"
clap = { version = "4.5", features = ["derive"] }
parking_lot = "0.12"
rand = "0.9"
static_assertions = "1.1"
rustc-hash = "2.1"
ahash = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }

# Only used for xtask
duct = "0.13"
fs_extra = "1.3"
glob = "0.3"

# Used in tests
indoc  = "2.0"
test-case  = "3.3"
env_logger = "0.11"


# The workspace libraries.
mcrl3-syntax = { path = "crates/syntax" }
mcrl3-utilities = { path = "crates/utilities" }
mcrl3-ldd = { path="crates/ldd" }