[package]
name = "mcrl3-aterm"
version.workspace = true
edition.workspace = true

[dependencies]
mcrl3-utilities.workspace = true

thiserror.workspace = true
hashbrown.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true