#![forbid(unsafe_code)]

use std::fmt;
use std::hash::Hash;
use std::hash::Hasher;

use merc_collections::BlockIndex;
use merc_lts::LTS;
use merc_lts::LabelIndex;
use merc_lts::LabelledTransitionSystem;
use merc_lts::StateIndex;
use rustc_hash::FxHashSet;

use super::BlockPartition;
use super::sort_topological;
use crate::Partition;
use crate::quotient_lts_naive;
use crate::tau_scc_decomposition_iterative;

/// The builder used to construct the signature.
pub type SignatureBuilder = Vec<(LabelIndex, BlockIndex)>;

/// The type of a signature. We use sorted vectors to avoid the overhead of hash
/// sets that might have unused values.
#[derive(Eq)]
pub struct Signature<'a>(&'a [(LabelIndex, BlockIndex)]);

impl<'a> Signature<'a> {
    pub fn new(slice: &'a [(LabelIndex, BlockIndex)]) -> Signature<'a> {
        Signature(slice)
    }

    pub fn as_slice(&self) -> &[(LabelIndex, BlockIndex)] {
        self.0
    }
}

impl Signature<'_> {
    // Check if other is a subset of self, excluding a specific element
    pub fn is_subset_of(&self, other: &[(LabelIndex, BlockIndex)], exclude: (LabelIndex, BlockIndex)) -> bool {
        let mut self_iter = self.as_slice().iter();
        let mut other_iter = other.iter().filter(|&&x| x != exclude);

        let mut self_item = self_iter.next();
        let mut other_item = other_iter.next();

        while let Some(&o) = other_item {
            match self_item {
                Some(&s) if s == o => {
                    // Match found, move both iterators forward
                    self_item = self_iter.next();
                    other_item = other_iter.next();
                }
                Some(&s) if s < o => {
                    // Move only self iterator forward
                    self_item = self_iter.next();
                }
                _ => {
                    // No match found in self for o
                    return false;
                }
            }
        }
        // If we finished self_iter without returning false, self is a subset
        true
    }
}

// This default implementation is actually different from the one generated by derive(Default).
#[allow(clippy::derivable_impls)]
impl Default for Signature<'_> {
    fn default() -> Self {
        Signature(&[])
    }
}

impl PartialEq for Signature<'_> {
    fn eq(&self, other: &Self) -> bool {
        self.as_slice() == other.as_slice()
    }
}

impl Hash for Signature<'_> {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.as_slice().hash(state)
    }
}

impl fmt::Debug for Signature<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_list().entries(self.as_slice().iter()).finish()
    }
}

/// Returns true if the label is the special tau_hat label for the given LTS.
pub fn is_tau_hat<L: LTS>(label: LabelIndex, lts: &L) -> bool {
    label == lts.num_of_labels()
}

/// Returns a special label that is not in the set of labels.
fn tau_hat<L: LTS>(lts: &L) -> LabelIndex {
    LabelIndex::new(lts.num_of_labels())
}

/// Returns the signature for strong bisimulation.
///
/// ```plain
///     sig(s, pi) = { (a, pi(t)) | s -a-> t in T }
/// ```
pub fn strong_bisim_signature<L: LTS, P: Partition>(
    state_index: StateIndex,
    lts: &L,
    partition: &P,
    builder: &mut SignatureBuilder,
) {
    builder.clear();

    for transition in lts.outgoing_transitions(state_index) {
        builder.push((transition.label, partition.block_number(transition.to)));
    }

    // Compute the flat signature, which has Hash and is more compact.
    builder.sort_unstable();
    builder.dedup();
}

/// Returns the branching bisimulation signature for branching bisimulation.
///
/// ```plain
///     sig(s, pi) = { (a, pi(t)) | s -tau-> s1 -> ... s_n -a-> t in T && pi(s) = pi(s_i) && ((a != tau) || pi(s) != pi(t)) }
/// ```
pub fn branching_bisim_signature<L: LTS, P: Partition>(
    state_index: StateIndex,
    lts: &L,
    partition: &P,
    builder: &mut SignatureBuilder,
    visited: &mut FxHashSet<StateIndex>,
    stack: &mut Vec<StateIndex>,
) {
    // Clear the builders and the list of visited states.
    builder.clear();
    visited.clear();

    // A stack used for depth first search of tau paths.
    debug_assert!(stack.is_empty(), "The stack should be empty");
    stack.push(state_index);

    while let Some(inner_state_index) = stack.pop() {
        visited.insert(inner_state_index);

        for transition in lts.outgoing_transitions(inner_state_index) {
            if lts.is_hidden_label(transition.label) {
                if partition.block_number(state_index) == partition.block_number(transition.to) {
                    // Explore the outgoing state as well, still tau path in same block
                    if !visited.contains(&transition.to) {
                        visited.insert(transition.to);
                        stack.push(transition.to);
                    }
                } else {
                    //  pi(s) != pi(t)
                    builder.push((transition.label, partition.block_number(transition.to)));
                }
            } else {
                // (a != tau) This is a visible action only reachable from tau paths with equal signatures.
                builder.push((transition.label, partition.block_number(transition.to)));
            }
        }
    }

    // Compute the flat signature, which has Hash and is more compact.
    builder.sort_unstable();
    builder.dedup();
}

/// The same as [branching_bisim_signature], but assuming that the input LTS is
/// topological sorted, and contains no tau-cycles.
pub fn branching_bisim_signature_sorted<L: LTS, P: Partition>(
    state_index: StateIndex,
    lts: &L,
    partition: &P,
    state_to_signature: &[Signature],
    builder: &mut SignatureBuilder,
) {
    builder.clear();

    for transition in lts.outgoing_transitions(state_index) {
        let to_block = partition.block_number(transition.to);

        if partition.block_number(state_index) == to_block {
            if lts.is_hidden_label(transition.label) {
                // Inert tau transition, take signature from the outgoing tau-transition.
                builder.extend(state_to_signature[transition.to].as_slice());
            } else {
                builder.push((transition.label, to_block));
            }
        } else {
            // Visible action, add to the signature.
            builder.push((transition.label, to_block));
        }
    }

    // Compute the flat signature, which has Hash and is more compact.
    builder.sort_unstable();
    builder.dedup();
}

/// The inductive version of [branching_bisim_signature_sorted]. Assumes that
/// the input LTS has no tau-cycles, and is topologically sorted.
pub fn branching_bisim_signature_inductive<L: LTS>(
    state_index: StateIndex,
    lts: &L,
    partition: &BlockPartition,
    state_to_key: &[BlockIndex],
    builder: &mut SignatureBuilder,
) {
    builder.clear();

    for transition in lts.outgoing_transitions(state_index) {
        let to_block = partition.block_number(transition.to);

        if partition.block_number(state_index) == to_block {
            if lts.is_hidden_label(transition.label) {
                debug_assert!(partition.is_element_marked(transition.to), "The state should be marked since it has an outgoing tau transition to the same block");
                // Inert tau transition, take signature from the outgoing tau-transition.
                builder.push((tau_hat(lts), state_to_key[transition.to]));
            } else {
                builder.push((transition.label, to_block));
            }
        } else {
            // Visible action, add to the signature.
            builder.push((transition.label, to_block));
        }
    }

    // Compute the flat signature, which has Hash and is more compact.
    builder.sort_unstable();
    builder.dedup();
}

/// Computes the weak bisimulation presignature.
///
/// The input lts must contain no tau-cycles.
pub fn weak_bisim_presignature_sorted<L: LTS, P: Partition>(
    state_index: StateIndex,
    lts: &L,
    partition: &P,
    state_to_taus: &[Signature],
    state_to_key: &[Option<usize>],
    builder: &mut SignatureBuilder,
) {
    builder.clear();
    builder.push((LabelIndex::new(0), partition.block_number(state_index))); // Add the inert tau transition to itself.
    for transition in lts.outgoing_transitions(state_index) {
        if lts.is_hidden_label(transition.label) {
            // Inert tau transition, take signature from the outgoing tau-transition.
            builder.push((tau_hat(lts), BlockIndex::new(state_to_key[transition.to].unwrap())));
        } else {
            for (label_after, color) in state_to_taus[transition.to].as_slice() {
                if lts.is_hidden_label(*label_after) {
                    builder.push((transition.label, *color));
                }
            }
        }
    }

    // Compute the flat signature, which has Hash and is more compact.
    builder.sort_unstable();
    builder.dedup();
}

/// Computes the weak bisimulation signature.
///
/// The input lts must contain no tau-cycles.
pub fn weak_bisim_signature_sorted_full<L: LTS, P: Partition>(
    state_index: StateIndex,
    lts: &L,
    partition: &P,
    state_to_taus: &[Signature],
    state_to_signature: &[Option<usize>],
    key_to_signature: &[Signature],
    builder: &mut SignatureBuilder,
) {
    builder.clear();
    builder.push((LabelIndex::new(0), partition.block_number(state_index))); // Add the inert tau transition to itself.
    for transition in lts.outgoing_transitions(state_index) {
        let to_block = partition.block_number(transition.to);

        if lts.is_hidden_label(transition.label) {
            // Inert tau transition, take signature from the outgoing tau-transition.
            builder.extend(key_to_signature[state_to_signature[transition.to].unwrap()].as_slice());
        } else {
            builder.push((transition.label, to_block));
            for (label_after, color) in state_to_taus[transition.to].as_slice() {
                if lts.is_hidden_label(*label_after) {
                    builder.push((transition.label, *color));
                }
            }
        }
    }

    // Compute the flat signature, which has Hash and is more compact.
    builder.sort_unstable();
    builder.dedup();
}

/// Computes the weak bisimulation signature.
///
/// The input lts must contain no tau-cycles.
pub fn weak_bisim_signature_sorted<L: LTS, P: Partition>(
    state_index: StateIndex,
    lts: &L,
    partition: &P,
    state_to_signature: &[Signature],
    builder: &mut SignatureBuilder,
) {
    builder.clear();
    builder.push((LabelIndex::new(0), partition.block_number(state_index))); // Add the inert tau transition to itself.
    for transition in lts.outgoing_transitions(state_index) {
        let to_block = partition.block_number(transition.to);

        if lts.is_hidden_label(transition.label) {
            // Inert tau transition, take signature from the outgoing tau-transition.
            builder.extend(state_to_signature[transition.to].as_slice());
        } else {
            builder.push((transition.label, to_block));
            for (label_after, color) in state_to_signature[transition.to].as_slice() {
                if lts.is_hidden_label(*label_after) {
                    builder.push((transition.label, *color));
                }
            }
        }
    }

    // Compute the flat signature, which has Hash and is more compact.
    builder.sort_unstable();
    builder.dedup();
}

/// This computes only tau signatures.
///
/// The input lts must contain no tau-cycles.
pub fn weak_bisim_signature_sorted_taus<L: LTS, P: Partition>(
    state_index: StateIndex,
    lts: &L,
    partition: &P,
    state_to_taus: &[Signature],
    builder: &mut SignatureBuilder,
) {
    builder.clear();
    builder.push((LabelIndex::new(0), partition.block_number(state_index))); // Add the inert tau transition to itself.
    for transition in lts.outgoing_transitions(state_index) {
        if lts.is_hidden_label(transition.label) {
            // Inert tau transition, take signature from the outgoing tau-transition.
            builder.extend(state_to_taus[transition.to].as_slice());
        }
    }
    // Compute the flat signature, which has Hash and is more compact.
    builder.sort_unstable();
    builder.dedup();
}

/// Perform the preprocessing necessary for branching bisimulation with the
/// sorted signature [branching_bisim_signature_sorted] and
/// [branching_bisim_signature_inductive].
///
/// # Details
///
/// Computes the tau-SCC decomposition of the LTS, quotients the LTS modulo the
/// tau-SCCs, and then sorts the states according to a reverse topological order
/// of the tau transitions, i.e., if there is a tau-transition from state s to
/// state t, then t appears before s in the ordering.
///
/// Returns the state of the preprocessed LTS corresponding to the given state.
/// If `eliminate_tau_selfloops` is true, then the tau self-loops are removed
/// after quotienting.
pub fn tau_cycle_elimination_and_reorder<L: LTS>(
    lts: L,
    state: StateIndex,
    eliminate_tau_selfloops: bool,
) -> (LabelledTransitionSystem<L::Label>, StateIndex) {
    let scc_partition = tau_scc_decomposition_iterative(&lts);
    let tau_loop_free_lts = quotient_lts_naive(&lts, &scc_partition, eliminate_tau_selfloops, eliminate_tau_selfloops);
    let mapped_state = StateIndex::new(*scc_partition.block_number(state));
    drop(lts);
    drop(scc_partition);

    // Sort the states according to the topological order of the tau transitions.
    let topological_permutation = sort_topological(
        &tau_loop_free_lts,
        |label_index, _| tau_loop_free_lts.is_hidden_label(label_index),
        true,
    )
    .expect("After quotienting, the LTS should not contain cycles");

    (
        LabelledTransitionSystem::new_from_permutation(tau_loop_free_lts, |i| topological_permutation[i]),
        topological_permutation[mapped_state],
    )
}
