[package]
name = "mcrl3_utilities"
version.workspace = true
edition.workspace = true

[dependencies]
ahash.workspace = true
bitstream-io.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
log.workspace = true