[package]
name = "merc_typecheck"

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ena.workspace = true
indoc.workspace = true
log.workspace = true
thiserror.workspace = true

merc_collections.workspace = true
merc_syntax.workspace = true
merc_utilities.workspace = true

[dev-dependencies]
rand.workspace = true
test-case.workspace = true