[package]
name = "mcrl2"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
mcrl2-macros.workspace = true
mcrl2-sys.workspace = true
merc_aterm.workspace = true
merc_collections.workspace = true
merc_tools.workspace = true
merc_unsafety.workspace = true
merc_utilities.workspace = true

itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
serde.workspace = true

[dev-dependencies]
merc_data.workspace = true
merc_syntax.workspace = true
merc_typecheck.workspace = true

[features]
# Enables the compiling rewriter option for mCRL2.
jittyc = []

# Enables the C++ trace option for mCRL2.
cpptrace = ["mcrl2-sys/cpptrace"]