[package]
name = "mcrl3_ltsgraph-lib"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mcrl3_lts.workspace = true
mcrl3_unsafety.workspace = true

cosmic-text.workspace = true
femtovg.workspace = true
glam.workspace = true
log.workspace = true
rand.workspace = true
tiny-skia.workspace = true