[package]
name = "merc-pbes"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "merc-pbes"
path = "src/main.rs"
# Avoid a rustdoc output filename collision with the `merc_pbes` library crate.
doc = false

[dependencies]
mcrl2.workspace = true
merc_explore = { workspace = true, features = ["clap"] }
merc_pbes.workspace = true
merc_tools.workspace = true
merc_unsafety.workspace = true
merc_utilities.workspace = true
merc_vpg = { workspace = true, features = ["clap"] }
oxidd.workspace = true

clap.workspace = true
duct.workspace = true
env_logger.workspace = true
log.workspace = true
which.workspace = true
