[package]
name = "mcrl3_number"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
mcrl3_utilities.workspace = true

bitstream-io.workspace = true
num.workspace = true
once_cell.workspace = true