[package]
name = "merc_symbolic"
description = "Implements various utility and I/O functionality for symbolic data structures, i.e., decision diagrams."
readme = "README.md"
version = "3.0.0"

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
# Derive additional traits for clap.
clap = ["dep:clap"]
# Enables keeping track of various performance metrics.
metrics = ["oxidd/statistics"]

[dependencies]
merc_aterm.workspace = true
merc_collections.workspace = true
merc_data.workspace = true
merc_io.workspace = true
merc_ldd.workspace = true
merc_lts.workspace = true
merc_utilities.workspace = true

clap = { workspace = true, optional = true }
duct.workspace = true
itertools.workspace = true
log.workspace = true
oxidd-core.workspace = true
oxidd-dump.workspace = true
oxidd-reorder.workspace = true
oxidd-rules-bdd.workspace = true
oxidd.workspace = true
rand.workspace = true
rustc-hash.workspace = true
streaming-iterator.workspace = true

[dev-dependencies]
merc_reduction.workspace = true
