[package]
name = "merc-lps"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mcrl2.workspace = true
merc_collections.workspace = true
merc_data.workspace = true
merc_explore = { workspace = true, features = ["clap"] }
merc_io.workspace = true
merc_ldd.workspace = true
merc_lts.workspace = true
merc_symbolic.workspace = true
merc_tools.workspace = true
merc_unsafety.workspace = true
merc_utilities.workspace = true

clap.workspace = true
env_logger.workspace = true
itertools.workspace = true
log.workspace = true
rand.workspace = true
serde_json.workspace = true
serde.workspace = true
streaming-iterator.workspace = true
thiserror.workspace = true

[dev-dependencies]
merc_reduction.workspace = true
tempfile.workspace = true