[workspace.package]
edition = "2024"
license = "BSL-1.0"
rust-version = "1.91.0"
version = "1.0.0"

# Add debug information to the release binaries.
[profile.release]
lto = "thin"
panic = "abort"
debug = "line-tables-only"

[workspace]
resolver = "3"
members = [
    "crates/mcrl2",
    "crates/mcrl2-macros",
    "crates/xtask",
    "lps",
    "pbes",
]

[workspace.dependencies]
clap = { version = "4.6", features = ["derive"] }
env_logger = "0.11"
itertools = "0.15"
log = "0.4"
parking_lot = "0.12"
rand = "0.10"
rayon = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
streaming-iterator = "0.1" 
thiserror = "2.0"
tempfile = "3.27"

# Dependencies used in procedural macros.
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

# Dependencies used in xtask
duct = "1.1"

# The workspace libraries.
mcrl2 = { path = "crates/mcrl2" }
mcrl2-macros = { path = "crates/mcrl2-macros" }
mcrl2-sys = { git = "https://github.com/MERCorg/mCRL2-sys", rev = "f7b05ac9046af260d9e605b44f8ac258815cfe1c" }
merc_collections = { path = "../../crates/collections" }
merc_data = { path = "../../crates/data" }
merc_explore = { path = "../../crates/explore", features = ["clap"] }
merc_io = { path = "../../crates/io" }
merc_lts = { path = "../../crates/lts", features = ["clap"] }
merc_reduction = { path = "../../crates/reduction" }
merc_symbolic = { path = "../../crates/symbolic" }
merc_tools = { path = "../../crates/tools" }
merc_unsafety = { path = "../../crates/unsafety" }
merc_syntax = { path = "../../crates/syntax" }
merc_utilities = { path = "../../crates/utilities" }
merc_vpg = { path = "../../crates/vpg" }

oxidd = { version = "0.11", features = ["manager-pointer"] }

# Use a local version of mCRL2-sys for development.
# [patch."https://github.com/MERCorg/mCRL2-sys"]
# mcrl2-sys = { path = "crates/mCRL2-sys" }

[patch.crates-io]
oxidd = { git = "https://github.com/mlaveaux/oxidd", rev = "eb50cb1b5aa8ea290696becbc4fe4296639c1367" }
oxidd-core = { git = "https://github.com/mlaveaux/oxidd", rev = "eb50cb1b5aa8ea290696becbc4fe4296639c1367" }
oxidd-dump = { git = "https://github.com/mlaveaux/oxidd", rev = "eb50cb1b5aa8ea290696becbc4fe4296639c1367" }
oxidd-reorder = { git = "https://github.com/mlaveaux/oxidd", rev = "eb50cb1b5aa8ea290696becbc4fe4296639c1367" }
oxidd-rules-bdd = { git = "https://github.com/mlaveaux/oxidd", rev = "eb50cb1b5aa8ea290696becbc4fe4296639c1367" }
oxidd-rules-ldd = { git = "https://github.com/mlaveaux/oxidd", rev = "eb50cb1b5aa8ea290696becbc4fe4296639c1367" }