use std::iter;

use itertools::Itertools;
use pest::error::ErrorVariant;
use pest_consume::Error;
use pest_consume::match_nodes;

use crate::ActDecl;
use crate::ActFrm;
use crate::Action;
use crate::Assignment;
use crate::Comm;
use crate::ComplexSort;
use crate::ConstructorDecl;
use crate::DataExpr;
use crate::DataExprUpdate;
use crate::EqnDecl;
use crate::EqnSpec;
use crate::IdDecl;
use crate::Mcrl2Parser;
use crate::MultiAction;
use crate::MultiActionLabel;
use crate::ProcDecl;
use crate::ProcessExpr;
use crate::RegFrm;
use crate::Rename;
use crate::Rule;
use crate::SortExpression;
use crate::StateFrm;
use crate::StateVarAssignment;
use crate::StateVarDecl;
use crate::UntypedDataSpecification;
use crate::UntypedProcessSpecification;
use crate::UntypedStateFrmSpec;
use crate::VarDecl;
use crate::parse_actfrm;
use crate::parse_dataexpr;
use crate::parse_process_expr;
use crate::parse_regfrm;
use crate::parse_sortexpr;
use crate::parse_statefrm;

/// Type alias for Errors resulting parsing.
pub(crate) type ParseResult<T> = std::result::Result<T, Error<Rule>>;
pub(crate) type ParseNode<'i> = pest_consume::Node<'i, Rule, ()>;

/// These functions are used to consume the parse tree generated by the `pest` parser into a syntax tree.
///
/// Functions that are private are only used by other functions within the module, especially within the `matches_nodes!` macro.
/// See `pest_consume` documentation for more details on how to use this macro. The main idea is to apply the consume functions to the children of a parse node whenver they matce the arm.
///
/// Functions that are `pub(crate)` are used by the pratt parser to consume the parse tree and build the syntax tree with priorities
/// and associativity. They are defined in `precedence.rs`.
#[pest_consume::parser]
impl Mcrl2Parser {
    // Although these are not public, they are the main entry points for consuming the parse tree.
    pub(crate) fn MCRL2Spec(spec: ParseNode) -> ParseResult<UntypedProcessSpecification> {
        let mut actions = Vec::new();
        let mut map = Vec::new();
        let mut eqn = Vec::new();
        let mut proc = Vec::new();
        let mut init = None;

        for child in spec.into_children() {
            match child.as_rule() {
                Rule::ActSpec => {
                    actions.extend(Mcrl2Parser::ActSpec(child)?);
                }
                Rule::MapSpec => {
                    map.append(&mut Mcrl2Parser::MapSpec(child)?);
                }
                Rule::EqnSpec => {
                    eqn.append(&mut Mcrl2Parser::EqnSpec(child)?);
                }
                Rule::ProcSpec => {
                    proc.append(&mut Mcrl2Parser::ProcSpec(child)?);
                }
                Rule::Init => {
                    if init.is_some() {
                        return Err(Error::new_from_span(
                            ErrorVariant::CustomError {
                                message: "Multiple init expressions are not allowed".to_string(),
                            },
                            child.as_span(),
                        ));
                    }

                    init = Some(Mcrl2Parser::Init(child)?);
                }
                _ => {
                    // Handle other rules if necessary
                }
            }
        }

        let data_specification = UntypedDataSpecification {
            map_decls: map,
            ..Default::default()
        };

        Ok(UntypedProcessSpecification {
            data_specification,
            init,
            ..Default::default()
        })
    }

    fn ActSpec(spec: ParseNode) -> ParseResult<Vec<ActDecl>> {
        match_nodes!(spec.into_children();
            [ActDecl(decls)..] => {
                Ok(decls.flatten().collect())
            },
        )
    }

    fn ActDecl(decl: ParseNode) -> ParseResult<Vec<ActDecl>> {
        let span = decl.as_span();
        match_nodes!(decl.into_children();
            [IdList(identifiers), SortProduct(args)] => {
                Ok(identifiers.iter().map(|name| ActDecl { identifier: name.clone(), args: args.clone(), span: span.into() }).collect())
            },
        )

    }

    fn SortProduct(sort: ParseNode) -> ParseResult<Vec<SortExpression>> {
        let mut iter = sort.into_children();

        // An expression of the shape SortExprPrimary ~ (SortExprProduct ~ SortExprPrimary)*
        let mut result = vec![Mcrl2Parser::SortExprPrimary(iter.next().unwrap())?];

        for mut chunk in &iter.chunks(2) {
            if chunk.next().unwrap().as_rule() == Rule::SortExprProduct {
                let sort = Mcrl2Parser::SortExpr(chunk.next().unwrap())?;

                result.push(sort);
            }
         
        }

        Ok(result)
    }    

    fn SortExprPrimary(sort: ParseNode) -> ParseResult<SortExpression> {
        parse_sortexpr(sort.children().as_pairs().clone())
    }

    pub(crate) fn DataSpec(spec: ParseNode) -> ParseResult<UntypedDataSpecification> {
        let mut map = Vec::new();
        let mut eqn = Vec::new();

        for child in spec.into_children() {
            match child.as_rule() {
                Rule::MapSpec => {
                    map.append(&mut Mcrl2Parser::MapSpec(child)?);
                }
                Rule::EqnSpec => {
                    eqn.append(&mut Mcrl2Parser::EqnSpec(child)?);
                }
                _ => {
                    // Handle other rules if necessary
                }
            }
        }

        Ok(UntypedDataSpecification {
            map_decls: map,
            eqn_decls: eqn,
            ..Default::default()
        })
    }

    pub(crate) fn StateFrmId(id: ParseNode) -> ParseResult<StateFrm> {
        match_nodes!(id.into_children();
            [Id(identifier)] => {
                return Ok(StateFrm::Id(identifier, Vec::new()));
            },
            [Id(identifier),DataExprList(expressions)] => {
                return Ok(StateFrm::Id(identifier, expressions));
            },
        );
    }

    fn MapSpec(spec: ParseNode) -> ParseResult<Vec<IdDecl>> {
        let mut ids = Vec::new();

        for decl in spec.into_children() {
            ids.append(&mut Mcrl2Parser::IdsDecl(decl)?);
        }

        Ok(ids)
    }

    fn Init(init: ParseNode) -> ParseResult<ProcessExpr> {
        match_nodes!(init.into_children();
            [ProcExpr(expr)] => {
                return Ok(expr);
            }
        );
    }

    fn ProcSpec(spec: ParseNode) -> ParseResult<Vec<ProcDecl>> {
        match_nodes!(spec.into_children();
            [ProcDecl(decls)..] => {
                return Ok(decls.collect())
            },
        );
    }

    fn ProcDecl(decl: ParseNode) -> ParseResult<ProcDecl> {
        let span = decl.as_span();
        match_nodes!(decl.into_children();
            [Id(identifier), VarsDeclList(params), ProcExpr(body)] => {
                return Ok(ProcDecl {
                    identifier,
                    params,
                    body,
                    span: span.into(),
                })
            },
            [Id(identifier), ProcExpr(body)] => {
                return Ok(ProcDecl {
                    identifier,
                    params: Vec::new(),
                    body,
                    span: span.into(),
                })
            }
        );
    }

    pub(crate) fn ProcExprAt(input: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(input.into_children();
            [DataExprUnit(expr)] => {
                return Ok(expr);
            },
        );
    }

    pub(crate) fn StateFrmExists(input: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(input.into_children();
            [VarsDeclList(variables)] => {
                return Ok(variables);
            },
        );
    }

    pub(crate) fn StateFrmForall(input: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(input.into_children();
            [VarsDeclList(variables)] => {
                return Ok(variables);
            },
        );
    }

    pub(crate) fn StateFrmMu(input: ParseNode) -> ParseResult<StateVarDecl> {
        match_nodes!(input.into_children();
            [StateVarDecl(variable)] => {
                return Ok(variable);
            },
        );
    }

    pub(crate) fn StateFrmNu(input: ParseNode) -> ParseResult<StateVarDecl> {
        match_nodes!(input.into_children();
            [StateVarDecl(variable)] => {
                return Ok(variable);
            },
        );
    }

    pub(crate) fn ActFrmExists(input: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(input.into_children();
            [VarsDeclList(variables)] => {
                return Ok(variables);
            },
        );
    }

    pub(crate) fn ActFrmForall(input: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(input.into_children();
            [VarsDeclList(variables)] => {
                return Ok(variables);
            },
        );
    }

    pub(crate) fn DataExpr(expr: ParseNode) -> ParseResult<DataExpr> {
        parse_dataexpr(expr.children().as_pairs().clone())
    }

    pub(crate) fn DataExprUnit(expr: ParseNode) -> ParseResult<DataExpr> {
        parse_dataexpr(expr.children().as_pairs().clone())
    }

    pub(crate) fn DataValExpr(expr: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(expr.into_children();
            [DataExpr(expr)] => {
                Ok(expr)
            },
        )
    }

    pub(crate) fn DataExprUpdate(expr: ParseNode) -> ParseResult<DataExprUpdate> {
        match_nodes!(expr.into_children();
            [DataExpr(expr), DataExpr(update)] => {
                Ok(DataExprUpdate { expr, update })
            },
        )
    }

    pub(crate) fn DataExprApplication(expr: ParseNode) -> ParseResult<Vec<DataExpr>> {
        match_nodes!(expr.into_children();
            [DataExprList(expressions)] => {
                return Ok(expressions);
            },
        )
    }

    pub(crate) fn DataExprWhr(expr: ParseNode) -> ParseResult<Vec<Assignment>> {
        match_nodes!(expr.into_children();
            [AssignmentList(assignments)] => {
                Ok(assignments)
            },
        )
    }

    pub(crate) fn AssignmentList(assignments: ParseNode) -> ParseResult<Vec<Assignment>> {
        match_nodes!(assignments.into_children();
            [Assignment(assignment)] => {
                return Ok(vec![assignment]);
            },
            [Assignment(assignment)..] => {
                return Ok(assignment.collect());
            },
        );
    }

    pub(crate) fn Assignment(assignment: ParseNode) -> ParseResult<Assignment> {
        match_nodes!(assignment.into_children();
            [Id(identifier), DataExpr(expr)] => {
                Ok(Assignment { identifier, expr })
            },
        )
    }

    pub(crate) fn DataExprSize(expr: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(expr.into_children();
            [DataExpr(expr)] => {
                return Ok(DataExpr::Size(Box::new(expr)));
            },
        )
    }

    fn DataExprList(expr: ParseNode) -> ParseResult<Vec<DataExpr>> {
        match_nodes!(expr.into_children();
            [DataExpr(expr)] => {
                return Ok(vec![expr]);
            },
            [DataExpr(expr)..] => {
                return Ok(expr.collect());
            },
        );
    }

    fn VarSpec(vars: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(vars.into_children();
            [VarsDeclList(ids)..] => {
                // Flatten the iterator of Vec<VarDecl> into a single Vec<VarDecl>
                let mut result = Vec::new();
                for id_vec in ids {
                    result.extend(id_vec);
                }
                return Ok(result);
            },
        );
    }

    pub(crate) fn VarsDeclList(vars: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(vars.into_children();
            [VarsDecl(decl)..] => {
                // Flatten the iterator of Vec<VarDecl> into a single Vec<VarDecl>
                return Ok(decl.flatten().collect());
            },
        );
    }

    fn VarsDecl(decl: ParseNode) -> ParseResult<Vec<VarDecl>> {
        let mut vars = Vec::new();

        let span = decl.as_span();
        match_nodes!(decl.into_children();
            [IdList(identifier), SortExpr(sort)] => {
                for id in identifier {
                    vars.push(VarDecl { identifier: id, sort: sort.clone(), span: span.into() });
                }
            },
        );

        Ok(vars)
    }

    pub(crate) fn SortExpr(expr: ParseNode) -> ParseResult<SortExpression> {
        parse_sortexpr(expr.children().as_pairs().clone())
    }

    pub(crate) fn Id(identifier: ParseNode) -> ParseResult<String> {
        Ok(identifier.as_str().to_string())
    }

    pub(crate) fn IdList(identifiers: ParseNode) -> ParseResult<Vec<String>> {
        match_nodes!(identifiers.into_children();
            [Id(ids)..] => {
                return Ok(ids.collect());
            },
        );
    }

    // Complex sorts
    pub(crate) fn SortExprList(inner: ParseNode) -> ParseResult<SortExpression> {
        Ok(SortExpression::Complex(
            ComplexSort::List,
            Box::new(parse_sortexpr(inner.children().as_pairs().clone())?),
        ))
    }

    pub(crate) fn SortExprSet(inner: ParseNode) -> ParseResult<SortExpression> {
        Ok(SortExpression::Complex(
            ComplexSort::Set,
            Box::new(parse_sortexpr(inner.children().as_pairs().clone())?),
        ))
    }

    pub(crate) fn SortExprBag(inner: ParseNode) -> ParseResult<SortExpression> {
        Ok(SortExpression::Complex(
            ComplexSort::Bag,
            Box::new(parse_sortexpr(inner.children().as_pairs().clone())?),
        ))
    }

    pub(crate) fn SortExprFSet(inner: ParseNode) -> ParseResult<SortExpression> {
        Ok(SortExpression::Complex(
            ComplexSort::FSet,
            Box::new(parse_sortexpr(inner.children().as_pairs().clone())?),
        ))
    }

    pub(crate) fn SortExprFBag(inner: ParseNode) -> ParseResult<SortExpression> {
        Ok(SortExpression::Complex(
            ComplexSort::FBag,
            Box::new(parse_sortexpr(inner.children().as_pairs().clone())?),
        ))
    }

    pub(crate) fn SortExprStruct(inner: ParseNode) -> ParseResult<SortExpression> {
        match_nodes!(inner.into_children();
            [ConstrDeclList(inner)] => {
                return Ok(SortExpression::Struct { inner });
            },
        );
    }

    pub(crate) fn ConstrDeclList(input: ParseNode) -> ParseResult<Vec<ConstructorDecl>> {
        match_nodes!(input.into_children();
            [ConstrDecl(decl)..] => {
                return Ok(decl.collect());
            },
        );
    }

    pub(crate) fn ProjDeclList(input: ParseNode) -> ParseResult<Vec<(Option<String>, SortExpression)>> {
        match_nodes!(input.into_children();
            [ProjDecl(decl)..] => {
                return Ok(decl.collect());
            },
        );
    }

    pub(crate) fn ConstrDecl(input: ParseNode) -> ParseResult<ConstructorDecl> {
        match_nodes!(input.into_children();
            [Id(name)] => {
                Ok(ConstructorDecl { name, args: Vec::new(), projection: None })
            },
            [Id(name), ProjDeclList(args)] => {
                Ok(ConstructorDecl { name, args, projection: None })
            },
            [Id(name), ProjDeclList(args), SortExpr(projection)] => {
                Ok(ConstructorDecl { name, args, projection: Some(projection) })
            },
        )
    }

    pub(crate) fn ProjDecl(input: ParseNode) -> ParseResult<(Option<String>, SortExpression)> {
        match_nodes!(input.into_children();
            [SortExpr(sort)] => {
                Ok((None, sort))
            },
            [Id(name), SortExpr(sort)] => {
                Ok((Some(name), sort))
            },
        )
    }

    pub(crate) fn DataExprListEnum(input: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(input.into_children();
            [DataExprList(expressions)] => {
                Ok(DataExpr::List(expressions))
            },
        )
    }

    pub(crate) fn DataExprBagEnum(input: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(input.into_children();
            [BagEnumEltList(elements)] => {
                Ok(DataExpr::Bag(elements))
            },
        )
    }

    fn BagEnumEltList(input: ParseNode) -> ParseResult<Vec<(DataExpr, DataExpr)>> {
        match_nodes!(input.into_children();
            [BagEnumElt(elements)..] => {
                return Ok(elements.collect());
            },
        )
    }

    fn BagEnumElt(input: ParseNode) -> ParseResult<(DataExpr, DataExpr)> {
        match_nodes!(input.into_children();
            [DataExpr(expr), DataExpr(amount)] => {
                return Ok((expr, amount));
            },
        )
    }

    pub(crate) fn DataExprSetEnum(input: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(input.into_children();
            [DataExprList(expressions)] => {
                Ok(DataExpr::Set(expressions))
            },
        )
    }

    pub(crate) fn DataExprSetBagComp(input: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(input.into_children();
            [VarDecl(variable), DataExpr(predicate)] => {
                Ok(DataExpr::SetBagComp { variable, predicate: Box::new(predicate) })
            },
        )
    }

    pub(crate) fn Number(input: ParseNode) -> ParseResult<DataExpr> {
        Ok(DataExpr::Number(input.as_str().into()))
    }

    fn VarDecl(decl: ParseNode) -> ParseResult<VarDecl> {
        let span = decl.as_span();
        match_nodes!(decl.into_children();
            [Id(identifier), SortExpr(sort)] => {
                Ok(VarDecl { identifier, sort, span: span.into() })
            },
        )
    }

    pub(crate) fn DataExprLambda(input: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(input.into_children();
            [VarsDeclList(vars)] => {
                Ok(vars)
            },
        )
    }

    pub(crate) fn DataExprForall(input: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(input.into_children();
            [VarsDeclList(vars)] => {
                Ok(vars)
            },
        )
    }

    pub(crate) fn DataExprExists(input: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(input.into_children();
            [VarsDeclList(vars)] => {
                Ok(vars)
            },
        )
    }

    pub(crate) fn ActFrm(input: ParseNode) -> ParseResult<ActFrm> {
        parse_actfrm(input.children().as_pairs().clone())
    }

    fn ActIdSet(actions: ParseNode) -> ParseResult<Vec<String>> {
        match_nodes!(actions.into_children();
            [IdList(list)] => {
                return Ok(list);
            },
        );
    }

    fn MultActId(actions: ParseNode) -> ParseResult<MultiActionLabel> {
        match_nodes!(actions.into_children();
            [Id(action), Id(actions)..] => {
                return Ok(MultiActionLabel { actions: iter::once(action).chain(actions).collect() });
            },
        );
    }

    fn MultActIdList(actions: ParseNode) -> ParseResult<Vec<MultiActionLabel>> {
        match_nodes!(actions.into_children();
            [MultActId(action), MultActId(actions)..] => {
                return Ok(iter::once(action).chain(actions).collect());
            },
        );
    }

    fn MultActIdSet(actions: ParseNode) -> ParseResult<Vec<MultiActionLabel>> {
        match_nodes!(actions.into_children();
            [MultActIdList(list)] => {
                return Ok(list);
            },
        );
    }

    fn ProcExpr(input: ParseNode) -> ParseResult<ProcessExpr> {
        parse_process_expr(input.children().as_pairs().clone())
    }

    fn ProcExprNoIf(input: ParseNode) -> ParseResult<ProcessExpr> {
        parse_process_expr(input.children().as_pairs().clone())
    }

    pub(crate) fn ProcExprId(input: ParseNode) -> ParseResult<ProcessExpr> {
        match_nodes!(input.into_children();
            [Id(identifier)] => {
                Ok(ProcessExpr::Id(identifier, Vec::new()))
            },
            [Id(identifier), AssignmentList(assignments)] => {
                Ok(ProcessExpr::Id(identifier, assignments))
            },
        )
    }

    pub(crate) fn ProcExprBlock(input: ParseNode) -> ParseResult<ProcessExpr> {
        match_nodes!(input.into_children();
            [ActIdSet(actions), ProcExpr(expr)] => {
                Ok(ProcessExpr::Block {
                    actions,
                    operand: Box::new(expr),
                })
            },
        )
    }

    pub(crate) fn ProcExprIf(input: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(input.into_children();
            [DataExpr(condition)] => {
                Ok(condition)
            },
        )
    }

    pub(crate) fn ProcExprIfThen(input: ParseNode) -> ParseResult<(DataExpr, ProcessExpr)> {
        match_nodes!(input.into_children();
            [DataExpr(condition), ProcExprNoIf(expr)] => {
                Ok((condition, expr))
            },
        )
    }

    pub(crate) fn ProcExprAllow(input: ParseNode) -> ParseResult<ProcessExpr> {
        match_nodes!(input.into_children();
            [MultActIdSet(actions), ProcExpr(expr)] => {
                Ok(ProcessExpr::Allow {
                    actions,
                    operand: Box::new(expr),
                })
            },
        )
    }

    pub(crate) fn ProcExprHide(input: ParseNode) -> ParseResult<ProcessExpr> {
        match_nodes!(input.into_children();
            [ActIdSet(actions), ProcExpr(expr)] => {
                Ok(ProcessExpr::Hide {
                    actions,
                    operand: Box::new(expr),
                })
            },
        )
    }

    fn ActionList(actions: ParseNode) -> ParseResult<Vec<Action>> {
        match_nodes!(actions.into_children();
            [Action(action), Action(actions)..] => {
                return Ok(iter::once(action).chain(actions).collect());
            },
        );
    }

    fn MultiActTau(_input: ParseNode) -> ParseResult<()> {
        Ok(())
    }

    pub(crate) fn MultAct(input: ParseNode) -> ParseResult<MultiAction> {
        match_nodes!(input.into_children();
            [MultiActTau(_)] => {
                return Ok(MultiAction { actions: Vec::new() });
            },
            [ActionList(actions)] => {
                return Ok(MultiAction { actions });
            },
        );
    }

    fn CommExpr(action: ParseNode) -> ParseResult<Comm> {
        match_nodes!(action.into_children();
            [Id(id), MultActId(multiact), Id(to)] => {
                let mut actions = vec![id];
                actions.extend(multiact.actions);

                return Ok(Comm {
                    from: MultiActionLabel { actions },
                    to
                });
            },
        );
    }

    fn CommExprList(actions: ParseNode) -> ParseResult<Vec<Comm>> {
        match_nodes!(actions.into_children();
            [CommExpr(action), CommExpr(actions)..] => {
                return Ok(iter::once(action).chain(actions).collect());
            },
        );
    }

    fn CommExprSet(actions: ParseNode) -> ParseResult<Vec<Comm>> {
        match_nodes!(actions.into_children();
            [CommExprList(list)] => {
                Ok(list)
            },
        )
    }

    pub(crate) fn ProcExprRename(input: ParseNode) -> ParseResult<ProcessExpr> {
        match_nodes!(input.into_children();
            [RenExprSet(renames), ProcExpr(expr)] => {
                Ok(ProcessExpr::Rename {
                    renames,
                    operand: Box::new(expr),
                })
            },
        )
    }

    pub(crate) fn ProcExprComm(input: ParseNode) -> ParseResult<ProcessExpr> {
        match_nodes!(input.into_children();
            [CommExprSet(comm), ProcExpr(expr)] => {
                Ok(ProcessExpr::Comm {
                    comm,
                    operand: Box::new(expr),
                })
            },
        )
    }

    pub(crate) fn Action(input: ParseNode) -> ParseResult<Action> {
        match_nodes!(input.into_children();
            [Id(id), DataExprList(args)] => {
                Ok(Action { id, args })
            },
            [Id(id)] => {
                Ok(Action { id, args: Vec::new() })
            },
        )
    }

    fn RenExprSet(renames: ParseNode) -> ParseResult<Vec<Rename>> {
        match_nodes!(renames.into_children();
            [RenExprList(renames)] => {
                Ok(renames)
            },
        )
    }

    fn RenExprList(renames: ParseNode) -> ParseResult<Vec<Rename>> {
        match_nodes!(renames.into_children();
            [RenExpr(renames)..] => {
                return Ok(renames.collect());
            },
        );
    }

    fn RenExpr(renames: ParseNode) -> ParseResult<Rename> {
        match_nodes!(renames.into_children();
            [Id(from), Id(to)] => {
                return Ok(Rename { from, to });
            },
        );
    }

    pub(crate) fn ProcExprSum(input: ParseNode) -> ParseResult<Vec<VarDecl>> {
        match_nodes!(input.into_children();
            [VarsDeclList(variables)] => {
                Ok(variables)
            },
        )
    }

    pub(crate) fn ProcExprDist(input: ParseNode) -> ParseResult<(Vec<VarDecl>, DataExpr)> {
        match_nodes!(input.into_children();
            [VarsDeclList(variables), DataExpr(expr)] => {
                Ok((variables, expr))
            },
        )
    }

    pub(crate) fn StateFrmDelay(input: ParseNode) -> ParseResult<StateFrm> {
        match_nodes!(input.into_children();
            [DataExpr(delay)] => {
                return Ok(StateFrm::Delay(delay));
            },
        );
    }

    pub(crate) fn StateFrmYaled(input: ParseNode) -> ParseResult<StateFrm> {
        match_nodes!(input.into_children();
            [DataExpr(delay)] => {
                return Ok(StateFrm::Yaled(delay));
            },
        );
    }

    pub(crate) fn StateFrmNegation(input: ParseNode) -> ParseResult<StateFrm> {
        match_nodes!(input.into_children();
            [StateFrm(state)] => {
                return Ok(StateFrm::Unary { op: crate::StateFrmUnaryOp::Negation, expr: Box::new(state) });
            },
        );
    }

    pub(crate) fn StateFrmDataValExprMult(input: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(input.into_children();
            [DataExpr(expr)] => {
                return Ok(expr);
            },
        );
    }

    pub(crate) fn StateFrmRightConstantMultiply(input: ParseNode) -> ParseResult<DataExpr> {
        match_nodes!(input.into_children();
            [ DataExpr(expr)] => {
                return Ok(expr);
            },
        );
    }

    pub(crate) fn StateFrmDataValExpr(input: ParseNode) -> ParseResult<StateFrm> {
        match_nodes!(input.into_children();
            [DataExpr(expr)] => {
                return Ok(StateFrm::DataValExpr(expr));
            },
        );
    }

    pub(crate) fn StateFrmDiamond(input: ParseNode) -> ParseResult<RegFrm> {
        match_nodes!(input.into_children();
            [RegFrm(formula)] => {
                return Ok(formula);
            },
        );
    }

    pub(crate) fn StateFrmBox(input: ParseNode) -> ParseResult<RegFrm> {
        match_nodes!(input.into_children();
            [RegFrm(formula)] => {
                return Ok(formula);
            },
        );
    }

    pub(crate) fn StateFrmSpec(input: ParseNode) -> ParseResult<UntypedStateFrmSpec> {
        match_nodes!(input.into_children();
            [StateFrm(state)] => {
                return Ok(UntypedStateFrmSpec {
                    data_specification: UntypedDataSpecification::default(),
                    formula: state
                });
            },
        );
    }

    fn IdsDecl(decl: ParseNode) -> ParseResult<Vec<IdDecl>> {
        let span = decl.as_span();
        match_nodes!(decl.into_children();
            [IdList(identifiers), SortExpr(sort)] => {
                let id_decls = identifiers.into_iter().map(|identifier| {
                    IdDecl { identifier, sort: sort.clone(), span: span.into() }
                }).collect();

                Ok(id_decls)
            },
        )
    }

    fn EqnSpec(spec: ParseNode) -> ParseResult<Vec<EqnSpec>> {
        let mut ids = Vec::new();

        match_nodes!(spec.into_children();
            [VarSpec(variables), EqnDecl(decls)..] => {
                ids.push(EqnSpec { variables, equations: decls.collect() });
            },
            [EqnDecl(decls)..] => {
                ids.push(EqnSpec { variables: Vec::new(), equations: decls.collect() });
            },
        );

        Ok(ids)
    }

    fn EqnDecl(decl: ParseNode) -> ParseResult<EqnDecl> {
        let span = decl.as_span();
        match_nodes!(decl.into_children();
            [DataExpr(condition), DataExpr(lhs), DataExpr(rhs)] => {
                Ok(EqnDecl { condition: Some(condition), lhs, rhs, span: span.into() })
            },
            [DataExpr(lhs), DataExpr(rhs)] => {
                Ok(EqnDecl { condition: None, lhs, rhs, span: span.into() })
            },
        )
    }

    fn StateFrm(input: ParseNode) -> ParseResult<StateFrm> {
        parse_statefrm(input.children().as_pairs().clone())
    }

    fn RegFrm(input: ParseNode) -> ParseResult<RegFrm> {
        parse_regfrm(input.children().as_pairs().clone())
    }

    fn StateVarDecl(input: ParseNode) -> ParseResult<StateVarDecl> {
        let span = input.as_span();
        match_nodes!(input.into_children();
            [Id(identifier), StateVarAssignmentList(arguments)] => {
                Ok(StateVarDecl {
                    identifier,
                    arguments,
                    span: span.into(),
                })
            },
            [Id(identifier)] => {
                Ok(StateVarDecl {
                    identifier,
                    arguments: Vec::new(),
                    span: span.into(),
                })
            }
        )
    }

    fn StateVarAssignmentList(input: ParseNode) -> ParseResult<Vec<StateVarAssignment>> {
        match_nodes!(input.into_children();
            [StateVarAssignment(assignments)..] => {
                Ok(assignments.collect())
            }
        )
    }

    fn StateVarAssignment(input: ParseNode) -> ParseResult<StateVarAssignment> {
        match_nodes!(input.into_children();
            [Id(identifier), SortExpr(sort), DataExpr(expr)] => {
                Ok(StateVarAssignment {
                    identifier,
                    sort,
                    expr,
                })
            }
        )
    }

    fn EOI(_input: ParseNode) -> ParseResult<()> {
        Ok(())
    }
}
