#![doc = include_str!("../README.md")]
#![forbid(unsafe_code)]

mod builder;
mod consume;
mod counterexample_formula;
mod parse;
mod precedence;
pub mod random_data_expression;
pub mod random_lps;
pub mod random_pbes;
mod spanned;
mod syntax_tree;
mod syntax_tree_display;
mod visitor;

pub(crate) use consume::*;
pub(crate) use precedence::*;
pub(crate) use syntax_tree::*;

pub use builder::apply_sort_expression;
pub use builder::apply_statefrm;
pub use builder::map_data_expr;
pub use counterexample_formula::generate_distinguishing_formula;
pub use counterexample_formula::generate_refinement_formula;
pub use parse::Mcrl2Parser;
pub use parse::Rule;
pub use parse::parse_action_names;
pub use parse::parse_allow_action_names;
pub use parse::parse_comm_expr_set;
pub use precedence::parse_sortexpr;
pub use random_data_expression::random_boolean_data_expression;
pub use random_data_expression::random_integer_data_expression;
pub use random_lps::make_process_specification;
pub use random_lps::random_lps;
pub use random_pbes::random_pbes;
pub use spanned::Span;
pub use spanned::Spanned;
pub use spanned::respan;
pub use syntax_tree::ActFrm;
pub use syntax_tree::ActFrmBinaryOp;
pub use syntax_tree::Action;
pub use syntax_tree::Assignment;
pub use syntax_tree::BagElement;
pub use syntax_tree::Bound;
pub use syntax_tree::CommExpr;
pub use syntax_tree::ComplexSort;
pub use syntax_tree::ConstructorDecl;
pub use syntax_tree::ConstructorId;
pub use syntax_tree::DataExpr;
pub use syntax_tree::DataExprBinaryOp;
pub use syntax_tree::DataExprKind;
pub use syntax_tree::DefId;
pub use syntax_tree::EqnSpecId;
pub use syntax_tree::EqnVarId;
pub use syntax_tree::EquationId;
pub use syntax_tree::FixedPointOperator;
pub use syntax_tree::IdDecl;
pub use syntax_tree::MapId;
pub use syntax_tree::ModalityOperator;
pub use syntax_tree::MultiAction;
pub use syntax_tree::MultiActionLabel;
pub use syntax_tree::PbesExpr;
pub use syntax_tree::ProcExprBinaryOp;
pub use syntax_tree::ProcessExpr;
pub use syntax_tree::Quantifier;
pub use syntax_tree::RegFrm;
pub use syntax_tree::Sort;
pub use syntax_tree::SortDecl;
pub use syntax_tree::SortExpression;
pub use syntax_tree::StateFrm;
pub use syntax_tree::StateFrmOp;
pub use syntax_tree::StateVarDecl;
pub use syntax_tree::UntypedDataSpecification;
pub use syntax_tree::UntypedPbes;
pub use syntax_tree::UntypedPres;
pub use syntax_tree::UntypedProcessSpecification;
pub use syntax_tree::UntypedStateFrmSpec;
pub use syntax_tree_display::line_column;
pub use visitor::SortDescend;
pub use visitor::try_visit_data_expr_mut;
pub use visitor::try_visit_sort_expr_with;
pub use visitor::visit_action_formula;
pub use visitor::visit_data_expr;
pub use visitor::visit_regular_formula;
pub use visitor::visit_sort_expr;
pub use visitor::visit_statefrm;
