[package]
name = "benchmarks_vpg"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
autobenches = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merc_utilities.workspace = true
merc_vpg.workspace = true
oxidd.workspace = true

criterion.workspace = true
rand.workspace = true

[[bench]]
name = "benchmarks_vpg"
harness = false
