import { HorizontalBox, Button, VerticalBox, Slider, ScrollView, CheckBox } from "std-widgets.slint";

export global Settings {
    // This property is only used internally to force refreshing the view.
    in property <bool> refresh;    
}

export component Application inherits Window {
    title: @tr("LTSView");
    icon: @image-url("../data/mcrl2-blue.png");

    preferred-width: 1280px;
    preferred-height: 720px;
    
    /// Render the simulation to an image.
    pure callback update_canvas(length, length, bool) -> image;
    
    Image {
        source: update_canvas(parent.width * 80%, parent.height, Settings.refresh);
    }
}

import { StandardButton, Button } from "std-widgets.slint";

export component ErrorDialog inherits Dialog {
    min-width: 100px;
    min-height: 100px;
    title: error_title;

    in property <string> error_text: "Message";
    in property <string> error_title: "Error!";

    VerticalLayout {
        Text {
            vertical-alignment: center;
            text: error_text;
        }
    }

    StandardButton { kind: ok; }
}