[package]
name = "mcrl3_unsafety"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
allocator-api2.workspace = true
hashbrown.workspace = true
rustc-hash.workspace = true