name: Cargo Fmt

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:    
    - name: Cache APT packages
      uses: actions/cache@v5
      with:
        path: /var/cache/apt/archives/*.deb
        key: apt-${{ runner.os }}-llvm-fontconfig-freetype-v1

    - name: Install Ubuntu Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm libfontconfig1-dev libfreetype6-dev

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.11

    - uses: actions/checkout@v7
      with:
        submodules: true

    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt

    - name: Run cargo fmt --check
      run: cargo +nightly fmt --all -- --check

    - name: Run cargo fmt --check for GUI tools
      run: cargo +nightly fmt --all -- --check
      working-directory: tools/gui

    - name: Run cargo fmt --check for mCRL2 tools
      run: cargo +nightly fmt --all -- --check
      working-directory: tools/mcrl2