name: clippy-action
on: [push, pull_request]
jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:    
    - name: Install Ubuntu Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: llvm, libfontconfig1-dev, libfreetype6-dev
        version: 1.0
      if: matrix.os == 'ubuntu-latest'

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy

    - uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-review'
        github_token: ${{ secrets.GITHUB_TOKEN }}