name: Semver Checks

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  semver:
    runs-on: ubuntu-latest

    steps:
    - name: Install stable rust
      uses: dtolnay/rust-toolchain@stable

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.11

    - name: Checkout the repository
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2
      with:
        feature-group: default-features
        exclude: benchmarks_aterm, benchmarks_aterm, benchmarks_sharedmutex, benchmarks_unsafety, benchmarks_utilities, merc-rewrite, merc-lts, merc-pbes, merc-lps, merc-stark, merc-sym, merc_rec-tests, merc_tools, merc_sabre-compiling, merc_sabre-ffi, merc_symbolic, merc_vpg, merc_typecheck
