name: Test with MCRL2_PATH

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:    
    - name: Install Ubuntu Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages:  build-essential, cmake, git, libboost-dev,  libfontconfig1-dev, libfreetype6-dev
        version: 1.0

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Install stable rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install nextest
      uses: taiki-e/install-action@nextest
      
    - name: Checkout mCRL2
      uses: actions/checkout@v6
      with:
        repository: mCRL2org/mCRL2
        sha: 4f357eccc1e8b9105db95742f9dda03e069f0918
        path: mCRL2
        submodules: true

    - name: Build mCRL2 toolset
      run: cmake --source-dir mCRL2 \
           --build-dir mCRL2/build \
           -DMCRL2_ENABLE_GUI_TOOLS=OFF \
           -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_C_COMPILER_LAUNCHER=sccache \
           -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
           && cmake --build mCRL2/build --config Release
    
    - name: Checkout the repository
      uses: actions/checkout@v6
      with:
        submodules: true

    - name: Run mcrl2 specific tests
      run: cargo nextest run --no-fail-fast -- --include-ignored mcrl2
      env:
        RUST_BACKTRACE: full
        RUST_LOG: debug
        RUSTC_WRAPPER: sccache
        MCRL2_PATH: mCRL2/build/stage/bin